CREATE TABLE robo_unit (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  uid VARCHAR(255) NOT NULL,
  config VARCHAR(255) NOT NULL
)

INSERT INTO robo_unit (uid, config) VALUES ('flywaySystem', 'httpUnit, serverUnit')